### ISSUE TITLE
Make use of `willReadFrequently` attribute for video

### ISSUE THREAD

**Issue by jwdallas** [fast-average-color/fast-average-color#100]
Chrome 108 is showing a message in console that the `willReadFrequently` attribute should be used for frequent uses of `getImageData`.

```
Canvas2D: Multiple readback operations using getImageData
are faster with the willReadFrequently attribute set to true.
```
The message provides this reference: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

![Screenshot 2022-12-08 at 1 20 44 PM](https://user-images.githubusercontent.com/1310725/206570961-397328a6-8856-49c7-9f2f-4f214700f4cd.png)

**Comment by hcodes** [comment]
Thanks! I will add support.

**Comment by hcodes** [comment]
v9.2.0.
