### ISSUE TITLE
Error import not found

### ISSUE THREAD

**Issue by GitHubish** [fast-average-color/fast-average-color#103]
I have several errors when installing the library in my project using typescript and Angular 15.

I use the last version 9.2.0

<img width="998" alt="image" src="https://user-images.githubusercontent.com/7701833/209931102-4f9b6e91-ebf4-435d-aaf8-21c7790dfb23.png">

**Comment by hcodes** [comment]
What is the TypeScript version?
/cc @GitHubish

**Comment by hcodes** [comment]
Please use Typescript version 4.9.4 and higher. In older versions there are no types for OffscreenCanvas.

Or use `fast-average-color` version v9.1.1.

**Comment by GitHubish** [comment]
oh! @hcodes thanks very much ;)
