### ISSUE TITLE
Broken in Firefox, random colors

### ISSUE THREAD

**Issue by clausbertels** [fast-average-color/fast-average-color#116]
@hcodes 

```
const fac = new FastAverageColor();
const articles = document.querySelectorAll('.article');

articles.forEach(article => {
    const img = article.querySelector('img');
    if (img) {
        fac.getColorAsync(img, { algorithm: 'dominant' })
            .then(color => {
                article.style.backgroundColor = color.rgb;
                article.style.color = color.isDark ? '#fff' : '#000';
            })
            .catch(e => console.log(e));
    }
});
```

In Firefox, my backgrounds get very random colors. Everything works perfectly in Safari and Chrome.

**Comment by hcodes** [comment]
[clausbertels](https://github.com/clausbertels) I can't reproduce the problem in this example, the result is the same in different browsers - https://fast-average-color.github.io/examples/background_async_dominant.html [code](https://github.com/fast-average-color/examples/blob/master/src/background_async_dominant/index.ts)

1. What version of Firefox?
2. What version of the fast-average-color package?
3. Are there any errors in the console?
4. To reproduce the problem, I need a full example with pictures.

**Comment by clausbertels** [comment]
Firefox 132 - not sure how to get anything but the latest version of fac using the browser.

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/d73e42fb-3a41-4b29-8c8f-413e5b578742">

<img width="1337" alt="image" src="https://github.com/user-attachments/assets/01936ee8-b42c-4380-b8a1-a07495e9b083">

```
<script src="https://unpkg.com/fast-average-color/dist/index.browser.min.js"></script>
...
<section class='info'>
    <?php foreach ($page->info()->toStructure() as $info): ?>
      <article class='article'> 
        <?php if ($file = $info->image()->toFile()): ?>
          <div class='img'>
            <img src="<?= $file->url() ?>">
          </div>
        <?php endif ?>
        <div class='text'>
          <p>
            <?= $info->article() ?>
          </p>
        </div>

      </article>
    <?php endforeach ?>
    <script>
      const fac = new FastAverageColor();
      const articles = document.querySelectorAll('.article');

      articles.forEach(article => {
          const img = article.querySelector('img');
          if (img) {
              fac.getColorAsync(img, { algorithm: 'dominant' })
                  .then(color => {
                      article.style.backgroundColor = color.rgb;
                      article.style.color = color.isDark ? '#fff' : '#000';
                  })
                  .catch(e => console.log(e));
          }
      });
    </script>
  </section>
```

Not sure if css is relevant?

**Comment by clausbertels** [comment]
Yes it did! So it was definitely my install, luckily not my website, thank you!

I refreshed Firefox on the about:support page and that fixed the issue. I must have messed with some config flags in the past that I forgot about.

**Comment by clausbertels** [comment]
Resolved
