### ISSUE TITLE
getColorAsync - return a Promise

### ISSUE THREAD

**Issue by 2xAA** [fast-average-color/fast-average-color#16]
Can we make `getColorAsync` return a Promise?
It would break the `.call` on the callback, though.

Maybe a third `getColor` function is needed?
I suppose the user could also wrap this, but it would be nice to have out of the box if the callback wasn't supplied.

Willing to make a PR for this, just need direction on what the best approach is.

**Comment by hcodes** [comment]
`.call` can be deleted. Add new property `resource` to `_prepareResult()`.

`getColorAsync(resource, callback, [options])` →`getColorAsync(resource, [options], [callback])`.
```js
// With callback
getColorAsync(resource, { width : 100, height: 100}, function(data) { console.log(data)});

// With promise
getColorAsync(resource).then(...);
```

```js
getColorAsync(resource, options, callback) {
if (callback) {
    this._getColorAsyncCallback(...);
} else {
    return this._getColorAsyncPromise(...);

}
}
```

Something like that.

**Comment by alun-430** [comment]
Hi, it is no problem in the Google browser.But it has problem in the Mobile browser.
And it tips: ''error: DOMException" and i get the color is white

**Comment by hcodes** [comment]
#21

**Comment by alun-430** [comment]
Hi, I'm very sorry for replying to your message in time. And thank you for your help to solve this problem at the same time. Can I ask you the other question:
That is what technologies do you use in the mobile as Front-end development engineer? We may not be one country, but technology has no national boundaries.So I hope you can tell me when you hava free time! Thank you very much!



------------------ 原始邮件 ------------------
发件人: "Denis Seleznev"<notifications@github.com>; 
发送时间: 2019年4月27日(星期六) 晚上7:19
收件人: "fast-average-color/fast-average-color"<fast-average-color@noreply.github.com>; 
抄送: "乌托邦"<960826725@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [fast-average-color/fast-average-color] getColorAsync - return aPromise (#16)




#21

**Comment by hcodes** [comment]
React, Vue and other.
