### ISSUE TITLE
It is failure  in the Mobile browser

### ISSUE THREAD

**Issue by alun-430** [fast-average-color/fast-average-color#20]
Hi, it is no problem in the Google browser.But it has problem in the Mobile browser.
And it tips: ''error: DOMException" and i get the color is white.
Info: In React.
Code:
` imgRef = (e) => {
        this.imgDom = e
    };

handleImageLoaded = () => {
        let that=this;
        if(this.imgDom){
            const fac = new FastAverageColor();
            fac.getColorAsync(this.imgDom, function (color) {
                that.setState({
                    bodyBgColor: color,
                });
            });
        }
    };

<div className={styles.showImg}>
                    <img
                        id="imgDom"
                        ref={(e) => this.imgRef(e)}
                        src={"https://n1-q.mafengwo.net/s13/M00/1D/C3/wKgEaVyhw-OARMlZAAHft8LZYM070.jpeg?imageMogr2%2Fthumbnail%2F%21750x750r%2Fstrip%2Fquality%2F90"}
                        alt=""
                    />
                </div>
`

**Comment by hcodes** [comment]
crossOrigin="anonymous" for a image.

**Comment by hcodes** [comment]
Problem solved?

**Comment by alun-430** [comment]
Hi, thank you for your solution and  solution address.
I added "crossOrigin={'anonymous'}" in <img>, the problem was solved in the Mobile browser.
The sample code：
```
**<img
    ref={this.imgRef}
    src={"https://n1-q.mafengwo.net/s13/M00/1D/C3/wKgEaVyhw-OARMlZAAHft8LZYM070.jpeg? 
    imageMogr2%2Fthumbnail%2F%21750x750r%2Fstrip%2Fquality%2F90"}
    alt=""
    crossOrigin={"anonymous"}
    onLoad={this.handleImageLoaded.bind(this)}
/>**
```

**Comment by alun-430** [comment]
> Problem solved?

Hi, thank you for your solution and solution address.
I added "crossOrigin={'anonymous'}" in , the problem was solved in the Mobile browser.
The sample code：

```
<img
    ref={this.imgRef}
    src={"https://n1-q.mafengwo.net/s13/M00/1D/C3/wKgEaVyhw-OARMlZAAHft8LZYM070.jpeg? 
    imageMogr2%2Fthumbnail%2F%21750x750r%2Fstrip%2Fquality%2F90"}
    alt=""
    crossOrigin={"anonymous"}
    onLoad={this.handleImageLoaded.bind(this)}
/>
```

**Comment by hcodes** [comment]
👍
