### ISSUE TITLE
'resource.addEventListener is not a function' when using getColorAsync

### ISSUE THREAD

**Issue by CesarGomezTissini** [fast-average-color/fast-average-color#25]
I wanna get dominant color from images using **getAsyncColor**. When I do this code in my Vue component:

``` javascript
dominantColor: async function(categories) {
  let predominantColor = []

  for (let category of categories) {
    let fac = new FastAverageColor()
    fac.getColorAsync(this.URL + category.image, 
       { algorithm: 'dominant' })
       .then(color => {
            console.log(color)
       })
       .catch(function(e) {
            console.error(e)
       })
   }
}
```
Chrome logs with a `resource.addEventListener is not a function` error. What should I do for this? 
`category.image`  is being gotted from a `Vuex` array state and `this.url` is a base url.

![Error](https://user-images.githubusercontent.com/47606542/57150801-db19cf80-6d94-11e9-84c1-e8eeb9ccab1a.png)

**Comment by hcodes** [comment]
```js
dominantColor: async function(categories) {
  let predominantColor = []

  for (let category of categories) {
    let fac = new FastAverageColor()
    let image = new Image();
    image.src = this.URL + category.image;
    fac.getColorAsync(image, { algorithm: 'dominant' })
       .then(color => {
            console.log(color)
       })
       .catch(function(e) {
            console.error(e)
       })
   }
}
```

**Comment by CesarGomezTissini** [comment]
Ok, now the problem is with tainted images from `CanvasRenderingContext2D`. [I tried this](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image) but nothing works.

**Comment by hcodes** [comment]
Do images have http protocol?
![file](https://user-images.githubusercontent.com/157520/57190202-8905b500-6f20-11e9-8d4e-b69aa0249565.png)
![http](https://user-images.githubusercontent.com/157520/57190205-8b680f00-6f20-11e9-8d3f-f67837ce9f8e.png)
There are browser restrictions for the file protocol.
You need to add `crossOrigin="anonymous"` attribute for a image.
Images must also have an `Access-Control-Allow-Origin: *` http header.
