### ISSUE TITLE
Typescript Importation Problem

### ISSUE THREAD

**Issue by flogh** [fast-average-color/fast-average-color#26]
Hey,

My problem is, that I'm simply unable to import the package after downloading it from npm, I'm using Typescript, via Angular. I'm not an expert but I'm having an issue that I never had before with a package.

I'm using the package as you said to :
import * as FastAverageColor from "fast-average-color"
const fac = new FastAverageColor();
"new FastAverageColor()": Cannot use 'new' with an expression whose type lacks a call or construct signature.

When I'm importing with the js way :
"const FastAverageColor = require('fast-average-color');"
I'm getting no error at first, but when I'm building, I get :
"Uncaught TypeError: FastAverageColor is not a constructor .."

So I don't know how to process, which step have I missed ?

Florian

**Comment by flogh** [comment]
Ok, 
I just managed to make things work, I had to import the package like this : 
import { FastAverageColor } from "fast-average-color/dist/index.es6"
Am I missing something or is it normal to import packages like this ?

**Comment by hcodes** [comment]
[v5.2.0](https://github.com/fast-average-color/fast-average-color/releases/tag/v5.2.0)
https://github.com/fast-average-color/fast-average-color#typescript
https://github.com/fast-average-color/fast-average-color/tree/master/dist
