### ISSUE TITLE
Omit colour from image?

### ISSUE THREAD

**Issue by helenburns** [fast-average-color/fast-average-color#37]
This is a brilliant tool, thank you. Just a question really. I am using it on logos, a lot of which are on white backgrounds. The average colour coming back to me is always very pale as a result, or white when I set it to the dominant algorithm. Is there a way I can choose to omit a colour from the calculation? If not this would be a really handy addition. Thanks for all your hard work.

**Comment by hcodes** [comment]
Good idea!

**Comment by hcodes** [comment]
[v6.0.0](https://github.com/fast-average-color/fast-average-color/releases/tag/v6.0.0)
[Get average color with ignored color](https://github.com/fast-average-color/fast-average-color/blob/master/docs/examples.md#get-average-color-with-ignored-color)

**Comment by helenburns** [comment]
Wow! Thank you so much! However, I've amended my code as your docs suggest and I'm loading the script from https://unpkg.com/fast-average-color/dist/index.min.js but it's still giving me the same results? There are no errors:

<img width="336" alt="Screenshot 2020-01-02 at 09 20 40" src="https://user-images.githubusercontent.com/475497/71659966-64790b80-2d41-11ea-943c-a9db72605297.png">

**Comment by hcodes** [comment]
Fixed.
v6.0.1

**Comment by helenburns** [comment]
Perfect! Works like a charm! Thank you so much!

**Comment by helenburns** [comment]
I know I might be pushing it but is there a way to omit two colours, rather than just the one.. where maybe a two colour combination is providing an unfavourable average colour? (think dark blue and bright orange only in a logo, with a white background - I still need to omit the white but the average colour of the blue and orange is a pale red which looks horrific and not complimentary at all!)

**Comment by hcodes** [comment]
Everything is possible)
But in a new issue.
