### ISSUE TITLE
looking to calculate avg color for area within picture

### ISSUE THREAD

**Issue by eyalfishler** [fast-average-color/fast-average-color#44]
I developed a browser extension that gives users the ability to choose a background dynamically (its just one part of what it does, it was designed to raise money for causes),
and using hsp algorithm to determine if the image is dark or light (based on google implementation i found in their background manager in chrome)

to determine the avg color of the image they check every 5 pixels

As you can see in the attached screenshot it works well, but there are cases where if the object
is centered and background is mostly bright, using avg for the whole picture seems not to do 
the trick (see attached)
I'm looking for a way to make the same calculation but based on some grid
I wonder how to calculate a pixel location in data based on x,y  or %  or region
**Do you have any suggestions?** your help with this might get more users to support a good cause :)
 

```---------------------------------
---------------------------------
|      |                 |      |
|      |                 |      |
|      |                 |      |
|      |                 |      |
---------------------------------
---------------------------------

 

code used: (data is getImageData from canvas)
``` length = data.data.length;
        i=-4
        blockSize=5
        while ( (i += blockSize * 4) < length ) {
          ++count;
          rgb.r += data.data[i];
          rgb.g += data.data[i+1];
          rgb.b += data.data[i+2];
        }

        // ~~ used to floor values
        rgb.r = ~~(rgb.r/count);
        rgb.g = ~~(rgb.g/count);
        rgb.b = ~~(rgb.b/count);
```
 

![Screenshot Dog black and white](https://user-images.githubusercontent.com/282129/74564312-9fb35080-4f23-11ea-8d3c-ad3f16304794.png)

![Screenshot 2020-02-14 12 12 22](https://user-images.githubusercontent.com/282129/74564566-2ec06880-4f24-11ea-8105-1aee8449f7f3.png)
![Screenshot 2020-02-14 12 12 48](https://user-images.githubusercontent.com/282129/74564579-34b64980-4f24-11ea-89b1-12a7c45ac4eb.png)

**Comment by hcodes** [comment]
Use [dominant algorithm](https://github.com/fast-average-color/fast-average-color/blob/master/docs/algorithms.md).
Demo page: https://fast-average-color.github.io/examples/define.html
![изображение](https://user-images.githubusercontent.com/157520/74613061-1f0b7480-511c-11ea-998d-401d944ab5cb.png)

Params for [area](https://github.com/fast-average-color/fast-average-color/blob/master/docs/api.md#getcolorasyncresource-options
): left, top, width, height.
