### ISSUE TITLE
Omit more than one colour

### ISSUE THREAD

**Issue by helenburns** [fast-average-color/fast-average-color#45]
Is there a way to omit two (or more) colours, rather than just the one.. where maybe a two colour combination is providing an unfavourable average colour? (think dark blue and bright orange only, in a logo, with a white background - I still need to omit the white but the average colour of the blue and orange is a pale red which looks horrific and not complimentary at all!)

**Comment by hcodes** [comment]
v6.2.0

**Comment by hcodes** [comment]
https://github.com/fast-average-color/fast-average-color/blob/master/docs/examples.md#get-average-color-with-multiple-ignored-colors

**Comment by helenburns** [comment]
Thanks so much for this update... although I'm not sure it's giving the correct result?

With the original code (this is taken out of context):
```
    ac.getColorAsync(item.querySelector('img'), {
        ignoredColor: [255, 255, 255, 255] // white
    })
```
I understandably get this...
<img width="56" alt="image" src="https://user-images.githubusercontent.com/475497/96988689-8f289080-151c-11eb-895d-ecee5dcc527f.png">
(The border and band at the bottom is the average of the blue, white and orange logo, with white omitted)

But with the updated code:
```
    ac.getColorAsync(item.querySelector('img'), {
        ignoredColor: [
            [255, 255, 255, 255], // white
            [242, 105, 15, 100] // orange
        ]
    })
```
I get exactly the same result! If I comment out the white line (so it's only omitting orange) I get this...
<img width="56" alt="image" src="https://user-images.githubusercontent.com/475497/96989121-255cb680-151d-11eb-8d1e-c52b825fd814.png">
But surely this should be a pale blue?

And if I comment out the orange line, so it's only omitting white, I get the same as before, which is as expected. It doesn't seem to be omitting the second colour... unless I'm missing something?

Regardless of all this, thanks so much for an awesome plugin, and nice to have it being actively improved and worked on, thanks!

**Comment by hcodes** [comment]
Thanks, I will check.

**Comment by helenburns** [comment]
Thank you - I should add that the image in question is literally only those three colours. Orange, white and blue.

**Comment by hcodes** [comment]
orange: ![изображение](https://user-images.githubusercontent.com/157520/96998858-ef2f2f00-153c-11eb-9075-e4866a5c7c0d.png)
white: ![изображение](https://user-images.githubusercontent.com/157520/96998883-fb1af100-153c-11eb-9bac-475b16d24046.png)
blue: ![изображение](https://user-images.githubusercontent.com/157520/96998941-0f5eee00-153d-11eb-94e4-e658f4875a75.png)

There is noise in the logo, plus anti-aliasing in the font. Because of this, the average color is not calculated correctly. I can recommend using the dominant algorithm.

```js
    ac.getColorAsync(item.querySelector('img'), {
        algorithm: 'dominant',
        ignoredColor: [
            [255, 255, 255, 255] // white
        ]
    })
```
https://github.com/fast-average-color/fast-average-color/blob/master/docs/algorithms.md

**Comment by helenburns** [comment]
Hi, that makes sense, although dominant doesn't really work either as some orange, blue and white logos now have just white borders and bands... which on a white background isn't working! This is despite white being omitted?! Does dominant work with omitting more than one colour?

For example, with this code:
```
    ac.getColorAsync(item.querySelector('img'), {
        algorithm: 'dominant',
        ignoredColor: [
            [255, 255, 255, 255], // white
            [242, 105, 15, 100] // orange
        ]
    })
```

I get this (for the logo before):
<img width="66" alt="image" src="https://user-images.githubusercontent.com/475497/97005150-edae3880-1535-11eb-8075-2620d58ecba0.png">
But I get white for these two logos (sorry I don't really want to show you the company logo itself as I'm a contractor!)
<img width="130" alt="image" src="https://user-images.githubusercontent.com/475497/97005257-1c2c1380-1536-11eb-8823-48800cfdbfe7.png">
(the dominant colour here is white)
and this:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/475497/97005300-29e19900-1536-11eb-80e7-8b9084c3341f.png">

So dominant ignores omitting colours? If so I'll have to go back to my slightly unsightly initial colours when only omitting white.

Thanks!

**Comment by hcodes** [comment]
Added treshold for ignored color:
```
    ac.getColorAsync(item.querySelector('img'), {
        algorithm: 'dominant',
        ignoredColor: [
            // red, green, blue, alpha, threshold (0-255)
            [255, 255, 255, 255, 5], // white
            [242, 105, 15, 100, 5] // orange
        ]
    })
```
v6.3.0.
