### ISSUE TITLE
Cannot use fast-average-color in a Typescript project.

### ISSUE THREAD

**Issue by kvanlaan** [fast-average-color/fast-average-color#48]
When I use the code sample I receive the following error:

ERROR Error: Uncaught (in promise): TypeError: fast_average_color__WEBPACK_IMPORTED_MODULE_4__ is not a constructor

**Comment by hcodes** [comment]
Fixed.
https://github.com/fast-average-color/fast-average-color/blob/master/docs/using.md#typescript
