### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by zausailov** [fast-average-color/fast-average-color#50]
This is my code
```
const fac = new FastAverageColor();
const img = new Image();
img.crossOrigin = "anonymous";
img.src = event.poster;
fac.getColorAsync(img)
            .then((color) => {
                setColor(color);
            })
            .catch((e) => {
                console.log(e);
            })
```
![Снимок экрана 2020-06-30 в 2 48 48 PM](https://user-images.githubusercontent.com/46808438/86123112-9cd78780-bae1-11ea-8f03-85f0c64de037.png)

Can anyone help me with this error?

**Comment by hcodes** [comment]
What browser version?

**Comment by zausailov** [comment]
> What browser version?

IE 11

**Comment by hcodes** [comment]
https://fast-average-color.github.io/examples/background_async.html
![VirtualBox_IE_11_01_07_2020_01_50_27](https://user-images.githubusercontent.com/157520/86184673-53b52100-bb3d-11ea-902d-73f88a73ffe9.png)

**Comment by hcodes** [comment]
with promise polyfill: https://www.npmjs.com/package/promise-polyfill
IE11 not supported arrow functions and Promise.

Is your code transpilled by Babel with polyfills?

**Comment by zausailov** [comment]
> with promise polyfill: https://www.npmjs.com/package/promise-polyfill
> IE11 not supported arrow functions and Promise.
> 
> Is your code transpilled by Babel with polyfills?

Yes, my code transpilled and I try to use Promise from promise-polyfill. Still same issue in IE

**Comment by hcodes** [comment]
Is there an error in IE on this page?
https://fast-average-color.github.io/examples/background_async.html

**Comment by hcodes** [comment]
And if the package is not imported, but connected to the page like this https://unpkg.com/fast-average-color@6.0.2/dist/index.js Will there be an error?

**Comment by hcodes** [comment]
Couldn't reproduce the error.
