### ISSUE TITLE
Weird Rollup Transformation

### ISSUE THREAD

**Issue by jsmith** [fast-average-color/fast-average-color#52]
Thanks for this great package! I'm having this weird issue with rollup though where some of the source code is being transformed in a way such that it errors out on chrome.

**Source Code**
```
        let
            red = arr[i],
            green = arr[i + 1],
            blue = arr[i + 2],
            alpha = arr[i + 3];
```
From [dominent.js](https://github.com/fast-average-color/fast-average-color/blob/master/src/algorithm/dominant.js#L10)

**Transformed Source Code**
```
`let,red=n[C],green=n[C+1],blue=n[C+2],alpha=n[C+3]`
```

**Error**
`Uncaught SyntaxError: Unexpected strict mode reserved word` which is caused by `let,` I think.

**Solution**
Place `red = arr[i]` on the same line as `let`. Also replace all other similar declarations using `let` in [simple.js](https://github.com/fast-average-color/fast-average-color/blob/master/src/algorithm/simple.js#L4), [sqrt.js](https://github.com/fast-average-color/fast-average-color/blob/master/src/algorithm/sqrt.js#L4) and [index.js](https://github.com/fast-average-color/fast-average-color/blob/master/src/index.js#L182).

One interesting thing to note is that similar style `const` declarations *do* work leading me to think this is some kind of bug with rollup?? Let me know what you think and thanks for the help!

**Comment by hcodes** [comment]
```js
let red = arr[i];
let green = arr[i + 1];
let blue = arr[i + 2];
let alpha = arr[i + 3];
```

**Comment by hcodes** [comment]
I'll fix it soon.

**Comment by hcodes** [comment]
This is a Rollup problem.

**Comment by jsmith** [comment]
Yeah definitely seems like a rollup issue. I'll file an issue in their repository. Thanks for changing your code in the meantime though!

**Comment by hcodes** [comment]
v6.0.3

**Comment by hcodes** [comment]
https://github.com/fast-average-color/fast-average-color/pull/53
