### ISSUE TITLE
Firefox Resource Error

### ISSUE THREAD

**Issue by kwaimind** [fast-average-color/fast-average-color#61]
Hey there, 

When using this lib, I'm getting the following error in Firefox: `FastAverageColor: incorrect sizes for resource "https://y39t3.csb.app/IMT.svg".`

Here is a [sandbox](https://codesandbox.io/s/fragrant-sea-y39t3) where I'm getting the error. Be great if you can let me know what I'm doing wrong. I tried using an Image constructor but have the same error there too.

**Comment by hcodes** [comment]
<img width="488" alt="изображение" src="https://user-images.githubusercontent.com/157520/99057921-82440d80-25ad-11eb-9eae-5c46661717e9.png">

**Comment by hcodes** [comment]
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1260.7">
Svg images don't have the width or height attribute, only viewBox.

**Comment by hcodes** [comment]
I will try to add an exception for the zero size for svg images.

**Comment by kwaimind** [comment]
Ah amazing, I'll try and catch that and add a size.

Thanks for a super fast response 💯

**Comment by kwaimind** [comment]
Thanks for fixing this. Looking forward to v6.2.1. Closing this issue.

**Comment by hcodes** [comment]
v6.3.0.
