### ISSUE TITLE
Add Docs for CORS

### ISSUE THREAD

**Issue by cupcakearmy** [fast-average-color/fast-average-color#65]
In Safari and Firefox it fails if the `crossorigin="anonymous"` is not set on the `img` elemnt.

See: https://github.com/lokesh/color-thief/issues/196#issue-680577085

**Comment by hcodes** [comment]
Thank you, I will add it to the documentation.

**Comment by cupcakearmy** [comment]
Feel free to close the issue then :)

**Comment by hcodes** [comment]
https://github.com/fast-average-color/fast-average-color/blob/master/README.md#unhandled-rejection-securityerror-the-operation-is-insecure
