### ISSUE TITLE
Library/package doesn't work?

### ISSUE THREAD

**Issue by BlackBearFTW** [fast-average-color/fast-average-color#70]
Hello,

I am using this library for the first time, but I am having issues with it

I originally want to use it in reactjs, so I installed the npm package and followed the documentation.

However whatever image I chose, the hex color was always #000000. So I decided to try to use it on jsFiddle, so I used unpkg to load it, but the same issue occurs.

https://jsfiddle.net/wbmosfcu/3/

I tried to give the image url directly as parameter to the function but I also tried to put it on an image element and pass that as parameter argument.

I also tried to use the async function but that just gives me the same error

What am I doing wrong?

**Comment by hcodes** [comment]
Use `.getColorAsync`.
