### ISSUE TITLE
typescript error @ 6.4.1

### ISSUE THREAD

**Issue by kephail** [fast-average-color/fast-average-color#79]
![Screenshot 2021-09-03 at 09 46 06](https://user-images.githubusercontent.com/3603778/131977626-68e4c120-b7e1-4b59-af8d-af409b9618bf.png)

Not sure if this is a localised issue as I haven't had time to look into it, but I am getting this error on 6.4.1 (which I notice was updated 1 week ago) and I do not get the error on 6.4.0

**Comment by hcodes** [comment]
What is the typescript version?
@kephail

**Comment by hcodes** [comment]
Please check new version: v6.4.2.

**Comment by charliejindra** [comment]
I'm getting the same issue and I'm on version 6.4.2... not sure if it's the same exact issue though because when I deprecated to 6.4.0 it gave me the same error.

**Comment by hcodes** [comment]
v7.0.1
