### ISSUE TITLE
Not getting dominant color from images with no background

### ISSUE THREAD

**Issue by anurag-roy** [fast-average-color/fast-average-color#81]
Hi, thanks for the amazing work on the library. Unfortunately, I am having some issues extracting dominant colors from cutout(?) images i.e. images without any background. I'm getting white as the dominant color every time.

<img width="504" alt="Screenshot 2021-09-10 at 12 04 53 AM" src="https://user-images.githubusercontent.com/53750093/132743389-9dea086a-e089-4c93-b355-e394d090bb3d.png">

Stackblitz: https://stackblitz.com/edit/fac-dominant-issue?file=index.ts

I have some test images([1](https://github.com/anurag-roy/fac-dominant-issue/blob/master/test-images/130.png), [2](https://github.com/anurag-roy/fac-dominant-issue/blob/master/test-images/94.png)) with which you can try it out.

I am using HTMLImageElement, is there anything to do with that? Because when the open the image in a new tab, I see a white background has been added. Any leads/help will be appreciated!

**Comment by yankovichv** [comment]
Same problem :(

**Comment by hcodes** [comment]
<img width="1393" alt="изображение" src="https://user-images.githubusercontent.com/157520/133004863-200a7327-3a96-45f1-b0f6-855134bc71fd.png">

```js
// Import stylesheets
import './style.css';

import FastAverageColor from 'fast-average-color';

const fac = new FastAverageColor();

const swatch = document.getElementById('swatch');
const imageInput = document.getElementById('imageInput') as HTMLInputElement;

imageInput.addEventListener('input', async () => {
  // Create the HTMLImageElement
  const image = document.getElementById('image') as HTMLImageElement;
  image.src = URL.createObjectURL(imageInput.files[0]);

  const averageColor = await fac.getColorAsync(image, {
    algorithm: 'dominant',
    ignoredColor: [0, 0, 0, 0],
  });
  console.log(averageColor);

  swatch.style.setProperty('background', averageColor.hexa);
});
```

**Comment by yankovichv** [comment]
Can you ignore two colors at once? For example, to immediately solve the problem of logos with a white background and logos with a transparent background.

**Comment by yankovichv** [comment]
Wow, I solved the problem! 
![image](https://user-images.githubusercontent.com/77819298/133009986-90664210-3a51-4033-8037-c90251838759.png)

**Comment by anurag-roy** [comment]
Thanks @hcodes. Working fine now!
