### ISSUE TITLE
fast_average_color_1.default is not a constructor

### ISSUE THREAD

**Issue by hzaun** [fast-average-color/fast-average-color#85]
node @12.22.0
ts @4.5.2
fast-average-color @7.0.1

Usage:

```
import FastAverageColor from "fast-average-color"

const fac = new FastAverageColor()
const color = fac.getColorFromArray4(data, {ignoredColor: [255, 255, 255, 255]}).slice(0, 3)
```

I can see that it decompiles to:

const fac = new fast_average_color_1.default();

There was a similar issue raised (https://github.com/fast-average-color/fast-average-color/issues/48), but I'm following the usage specified there, and still getting the error.

**Comment by hcodes** [comment]
I can't reproduce the problem. The environment is similar.
<img width="1096" alt="изображение" src="https://user-images.githubusercontent.com/157520/149652257-c3905aa7-172e-4de9-829d-60d87f8965db.png">
https://github.com/fast-average-color/example-ts

**Comment by hzaun** [comment]
[I can replicate the issue](https://github.com/hzaun/example-ts/tree/fac-701) by removing the `"esModuleInterop": true` flag in tsconfig, but this is not a change I can make in my codebase.

Ps. I was earlier using [fast-average-color @6.0.1](https://github.com/hzaun/example-ts/tree/fac-601), where I could simply do:

<img width="334" alt="Screenshot 2022-01-18 at 2 55 52 PM" src="https://user-images.githubusercontent.com/20596877/149908693-3e92eaab-182a-4886-928b-69e628e1819f.png">

---
https://github.com/hzaun/example-ts/tree/fac-601
https://github.com/hzaun/example-ts/tree/fac-701

**Comment by hcodes** [comment]
Use named exports - v8.0.0
