### ISSUE TITLE
Can't find variable: Image

### ISSUE THREAD

**Issue by Tomvkgames** [fast-average-color/fast-average-color#90]
Calling
```
        const fac = new FastAverageColor();
        fac.getColorAsync(result.base64).then(color=>console.log(color));
```

Gives the error "[Unhandled promise rejection: ReferenceError: Can't find variable: Image]"

```
FastAverageColor.prototype.getColorAsync = function (resource, options) {
            var _a;
            if (!resource) {
                return Promise.reject(getError('call .getColorAsync() without resource.'));
            }
            if (typeof resource === 'string') {
                var img = new Image();
                img.crossOrigin = (_a = options === null || options === void 0 ? void 0 : options.crossOrigin) !== null && _a !== void 0 ? _a : '';
                img.src = resource;
                return this.bindImageEvents(img, options);
            }
```

the error is in the line ```var img = new Image();```

When I ctrl + leftClick on Image in VSC it goes to a definition outside of the project, but native file from VSC: ```C:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\lib.dom.d.ts```

**Comment by hcodes** [comment]
Does the code run in the browser?
Package Version, Browser, OS?

**Comment by hcodes** [comment]
https://github.com/fast-average-color/fast-average-color/blob/master/docs/using.md#nodejs
