### ISSUE TITLE
getColorFromArray4() returns gray color for a red image

### ISSUE THREAD

**Issue by astoilkov** [fast-average-color/fast-average-color#99]
Is this the correct usage? 
```ts
const byteArray = new Uint8Array(hex.length / 2)
for (let i = 0; i < hex.length / 2; i++) {
  const index = i * 2
  byteArray[i] = Number.parseInt(hex.slice(index, index + 2), 16)
}

const rgba = fastAverageColor.prepareResult(fastAverageColor.getColorFromArray4(byteArray)).rgba
```

I'm trying to do the operation synchrously.

Example for a `hex` value is: `89504E470D0A1A0A0000000D4948445200000020000000200806000000737A7AF400000370494441545885AD576D72DA48107D3D925DF85774838C17E2925381684FB0F804E1064B4EB0EC09022758E704B16F404E607C8260D85A6B2BA2229F60E1572822E9ED0F240268C4977955FAC1B4E87ED33DDD6F24D803E58B6A030AEF04D010710078A9A90F724C2014A21BFC3BFCBCAB4FD9F682765D6DE1E403441A0238BB38253006D98DA7D69F61D81F1F4CA0E2D6DA14FCB16B60131121AE037FD0D98B80D69E639F2577F899E2E7A21F7D5757A66CE408E857AF3DCBB6EF0EDD7511088CE328BA0ABFFED32F24A0B5E75867C9B763075F21F15D9D2F67422D07B7CF92D59D930F246F093C1D10EC89E42DC8FB6C4D80ACB40B2C08D8A5A485B59A13B81EF9C3E6E871A049BE5F2142DE2F3F2426F3654C48BE1F3D0EF4C81F3699E07A8D9B57716BED255269ABC9E9975CEA995C05FEDFBDECA7D69E8393995EAFE3C2EEBA1AD3D27839C5FAD56BCFB6ED2F6B1B5B94C206000B27ED5DEA9E3A36060780D0F7C3DCA295984EBE6395E26B00CDB404D2303924446F23B50D5672626E65917700A0CA17D586085EE4821393786A759F4B209E593DD32116C0295F541B0A0AC6DD036C6D1BA3BB200CFB63906DA3D192BA12C098E663EC3EC3C81FDE98D685F4140C878FC4E418BB5F737A9F5B1379A120F2D6F0FA7F470D5E0C4F995645CC65790E28E68E524563566BEFA87A20C0CB1C29E04909991F1E00AC525CD01DFBA37C5135FA12325414314E36017E3F1601516899D629D25788D933192152FFE5B266FCE33E28BBD526447E331A63F6543CB37A9992AD43017F55DCDA87438357DC5A5B443E996C2426F1CCEA49CAF24644E629273A4CD8178576D6A2244211764174037F98EFE795A06FEA09D55B11B4367513818FA3C7416B21C7B69C7E4B0DE3388AAEF0E334B44B712F3727C887C01F1A05A67C59ED0AE622B30D1167E7A1EF870A486594E800A954DAF61D4A5327C28FC67A7998C03CD701C4515C685BDD043A9974AFDC092B6EB5FF33EDBC1DF9C3A6D69E93DE9640302C9AEB0B1F97356E0EBE9AC1FCA5B49484993C4751F46BD1EDE710027389577A5967CCD772CBEE652448DE086431AC367D646C22406212C7517DE3B57C41427B8EF10002081E079BBFA64C04C887686AD54D0A6B14A330EC8F037FE86507F359203A813FF48AE4DD482043E00FDA1167E7043ECEAFDBE681B5122F7D8FE46DC4D979E00F76EB8C6DD0DA73B4EB6E9569EDBA7A1F25FD1F1655BEBD33EDAD050000000049454E44AE426082`

**Comment by astoilkov** [comment]
BTW, I already use the `byteArray` to create a object URL:
```ts
URL.createObjectURL(new Blob([byteArray], { type: 'application/octet-stream' }))
```

**Comment by astoilkov** [comment]
It doesn't work. Here is a sandbox showing the result:
https://codesandbox.io/s/festive-bogdan-pe0ivr?file=/src/index.js

<img width="1378" alt="CleanShot 2022-10-13 at 08 29 21@2x" src="https://user-images.githubusercontent.com/884810/195509522-a094389f-eaea-45f1-b3db-79f2f05f1150.png">

**Comment by hcodes** [comment]
Yes, the color is incorrect.

Checked in https://fast-average-color.github.io/examples/define.html

I will check the correctness of the code again later.

**Comment by hcodes** [comment]
How is the `hex` variable obtained?

**Comment by astoilkov** [comment]
I'm reading it from the Chrome `Favicons` database using this SQLite query:
```sql
SELECT
  icon_id as faviconId,
  hex(image_data) as hex
FROM
  favicon_bitmaps
WHERE
  width = 32
  AND height = 32;
```

**Comment by hcodes** [comment]
byteArray.length = 642 bytes
The array must be a multiple of 4. In fact - 642/4 = 160.5
This means that incorrect data is received at the input of the method.

**Comment by hcodes** [comment]
I saved the icon in the browser. It just takes 642 bytes.
![31f2a580-da7a-4c87-9eea-5b4aba22bcc5](https://user-images.githubusercontent.com/157520/210099492-7bae78ea-7a9e-4bde-a547-9f0de2963b28.png)

**Comment by hcodes** [comment]
<img width="940" alt="изображение" src="https://user-images.githubusercontent.com/157520/210099869-39e4c1ee-c5ff-4261-b03f-cd3ee2bcd09c.png">
```js
const fs = require('fs');

const hex = `89504E470D0A1A0A0000000D4948445200000020000000200806000000737A7AF400000249494441545885ED964D4B545118C77FE7CE9D3BD31B318C43D0584E35489410D5C65E286AD1C695825FC0BE4108EA7770D3565CB8709304AD0B2130226950434DE605B37C9B684A6C8C663A77C6A785245A74993363D3427F7076E7FFFCFFF7DEE79EF3C001FB1D65B259441460796D514A6D561DE07E53D3E556A55AA32267CF2915F141280047A3105410046CC001E42FB5CA8006DC02FCC84211F8F61DD617453E672D6B7106A61F2E2CBCD855E3041C7902439B5016907FBD26E1F90538BD9DFC190CD5C378E74AC218E0700FAE0A94EA1D4040DAE1AE75036E023E93C6D92B6EC135AB19CEFF0F738038345B4D1035524522D0D707A150CD01C270920CBC34FA76918888EB8A6432221D1D35F5C0079824093346C28606915C4EB619191189C7AB0AB00A298BAD83A57A3A3B219180EE6E70CC4A091C2605C99ADEC04EA6A644DADA2AAE958555CB6F781F78128B41B4F29EB6004BEF95F9E020B4B4C0C040C59212882D50AAC97862027A7B6174D4582A50240DE3C63DA0B5483E2FD2D323120854FD1BAEC0B4BD016B46B17D3E181E86FE7E989B337EEA9D6461DD9E87D52B26AA5C0EBABA6A32FEC557F868BD83B4916AD368E0F1240DF3D66B18DFB38A86BC8104807F1A9ED67B16C8C2DB063806C02588CEC258BDCC5760F60E5C84DDA7A0FDC071DAAF2B75BB11CE9C12092BA58E3B7028BC755FF8D91A4ABD8717A54A889401F70B680D0594CA2F89AC7D82A58452AF1E158B8F53B0F17B803F1011DFF2F2B2D3A8B5432060A3B58D6D7B07D0BA443058A65070DFDBB68EC562AE52AAECA939605FF31344D0B81E68373ED70000000049454E44AE426082`;


const byteArray = new Uint8Array(hex.length / 2)
for (let i = 0; i < hex.length / 2; i++) {
  const index = i * 2
  byteArray[i] = Number.parseInt(hex.slice(index, index + 2), 16)
}

fs.writeFileSync('file.unknown', byteArray);
```

**Comment by astoilkov** [comment]
Thanks for investigating!

Do you know what I should do to make this work? I'm not sure I understand what I'm doing wrong.

**Comment by ryanmattos** [comment]
Facing same issue, but the byteArr.length is multiple of 4, yet still returns the gray color

![image](https://github.com/user-attachments/assets/032417d9-35d1-4470-bc83-cd0d9c83b50d)
![image](https://github.com/user-attachments/assets/8f2b61dc-e1bd-4de9-9407-1e093b88e531)

> The second log is arrBuffer.byteLength / 4;

> Either `color1` and `color2` are obtained from same image. The `color1` uses `getColorFromArray4()`  from buffered input file image and `color2` uses `getColor` the very same image, but from resources.

**Comment by hcodes** [comment]
Simply loading an image into an ArrayBuffer is not enough. JPEG image must first be decoded into a bitmap (an array where each pixel takes up 4 bytes) and then you can use `getColorFromArray4()`.

**Comment by ryanmattos** [comment]
Thanks for responding!

I will investigate further and check the results later
